### ISSUE TITLE
Slight technical error in PoS paper

### ISSUE THREAD

**Issue by ebuchman** [TheBlueMatt/bitcoinninja#11]
Section 2.3: "It can be mathematically proven that given only a synchronous network it is impossible to
achieve distributed consensus in a cryptographically guaranteed way [1]"

Should be "asynchronous", not "synchronous".

(not sure if this the right place for this issue, but wasn't sure where the paper's source is)

**Comment by apoelstra** [comment]
Hi @ebuchman, here is fine (unless @TheBlueMatt jumps in to say no). Thanks for the report, I will fix it.

**Comment by apoelstra** [comment]
Both pos.pdf and alts.pdf are fixed now. The text explaining Bitcoin's "weak synchronicity" is slightly expanded in alts.pdf.

Thanks!, this can be closed now.
